### ISSUE TITLE
yml file for environment setup is not cross-platform

### ISSUE THREAD

**Issue by SolaWeng** [Jin-Fang/marl-optimal-execution#1]
The current yml file does not work on Windows as it prompts errors ResolvePackageNotFound.

**Comment by SolaWeng** [comment]
yml file also didn't work under ubuntu

**Comment by SolaWeng** [comment]
set up with only CPU, the following error occurred when running the rmsc02.sh file:

=========================================================
ABIDES: Agent-Based Interactive Discrete Event Simulation
=========================================================

Simulation Start Time: 2021-04-30 00:41:45.206792
Configuration seed: 123456789


--- Simulation time: 2019-06-28 00:00:00, messages processed: 0, wallclock elapsed: 0 days 00:00:00.000017 ---


--- Simulation time: 2019-06-28 15:08:23.521479512, messages processed: 100000, wallclock elapsed: 0 days 00:00:34.966905 ---

Final holdings for MARKET_MAKER_AGENT_1: { JPM: 9622, CASH: -947737148 }.  Marked to market: 9796182
Final holdings for ZI_AGENT_2: { JPM: 259, CASH: -15583649 }.  Marked to market: 10190736
Final holdings for ZI_AGENT_3: { JPM: 600, CASH: -50015900 }.  Marked to market: 9693100
Final holdings for ZI_AGENT_4: { JPM: 376, CASH: -27667900 }.  Marked to market: 9749740
Final holdings for ZI_AGENT_5: { JPM: -131, CASH: 23963350 }.  Marked to market: 10926885
Final holdings for ZI_AGENT_6: { JPM: -540, CASH: 64888360 }.  Marked to market: 11150260
Final holdings for ZI_AGENT_7: { JPM: -70, CASH: 16981840 }.  Marked to market: 10015790
Final holdings for ZI_AGENT_8: { JPM: -98, CASH: 19887374 }.  Marked to market: 10085022
Final holdings for ZI_AGENT_9: { JPM: 101, CASH: 102157 }.  Marked to market: 10153172
Final holdings for ZI_AGENT_10: { CASH: 10455200 }.  Marked to market: 10455200
Final holdings for ZI_AGENT_11: { CASH: 10358400 }.  Marked to market: 10358400
Final holdings for ZI_AGENT_12: { JPM: 48, CASH: 5357928 }.  Marked to market: 10134648
Final holdings for ZI_AGENT_13: { CASH: 10115100 }.  Marked to market: 10115100
Final holdings for ZI_AGENT_14: { JPM: -258, CASH: 36134168 }.  Marked to market: 10459298
Final holdings for ZI_AGENT_15: { JPM: -256, CASH: 35807510 }.  Marked to market: 10331670
Final holdings for ZI_AGENT_16: { JPM: 111, CASH: -855203 }.  Marked to market: 10190962
Final holdings for ZI_AGENT_17: { JPM: -311, CASH: 41428467 }.  Marked to market: 10479302
Final holdings for ZI_AGENT_18: { JPM: 4, CASH: 10104397 }.  Marked to market: 10502457
Final holdings for ZI_AGENT_19: { JPM: -386, CASH: 48644646 }.  Marked to market: 10231856
Final holdings for ZI_AGENT_20: { JPM: 166, CASH: -5936570 }.  Marked to market: 10582920
Final holdings for ZI_AGENT_21: { JPM: 283, CASH: -17867342 }.  Marked to market: 10295403
Final holdings for ZI_AGENT_22: { JPM: -244, CASH: 34627040 }.  Marked to market: 10345380
Final holdings for ZI_AGENT_23: { JPM: 37, CASH: 6749687 }.  Marked to market: 10431742
Final holdings for ZI_AGENT_24: { JPM: -500, CASH: 60520700 }.  Marked to market: 10763200
Final holdings for ZI_AGENT_25: { JPM: -100, CASH: 20291600 }.  Marked to market: 10340100
Final holdings for ZI_AGENT_26: { JPM: -723, CASH: 83007887 }.  Marked to market: 11058542
Final holdings for ZI_AGENT_27: { JPM: 100, CASH: 2200 }.  Marked to market: 9953700
Final holdings for ZI_AGENT_28: { JPM: -301, CASH: 40379851 }.  Marked to market: 10425836
Final holdings for ZI_AGENT_29: { JPM: -500, CASH: 60701600 }.  Marked to market: 10944100
Final holdings for ZI_AGENT_30: { JPM: 6, CASH: 9587792 }.  Marked to market: 10184882
Final holdings for ZI_AGENT_31: { JPM: -261, CASH: 37097173 }.  Marked to market: 11123758
Final holdings for ZI_AGENT_32: { JPM: -500, CASH: 60813000 }.  Marked to market: 11055500
Final holdings for ZI_AGENT_33: { JPM: -700, CASH: 80309200 }.  Marked to market: 10648700
Final holdings for ZI_AGENT_34: { JPM: -500, CASH: 60686400 }.  Marked to market: 10928900
Final holdings for ZI_AGENT_35: { JPM: -270, CASH: 37387370 }.  Marked to market: 10518320
Final holdings for ZI_AGENT_36: { JPM: -376, CASH: 48150984 }.  Marked to market: 10733344
Final holdings for ZI_AGENT_37: { JPM: 300, CASH: -19845600 }.  Marked to market: 10008900
Final holdings for ZI_AGENT_38: { JPM: -85, CASH: 18670955 }.  Marked to market: 10212180
Final holdings for ZI_AGENT_39: { JPM: -374, CASH: 47631147 }.  Marked to market: 10412537
Final holdings for ZI_AGENT_40: { JPM: 503, CASH: -40412161 }.  Marked to market: 9643884
Final holdings for ZI_AGENT_41: { JPM: -279, CASH: 38182070 }.  Marked to market: 10417385
Final holdings for ZI_AGENT_42: { JPM: -226, CASH: 32953488 }.  Marked to market: 10463098
Final holdings for ZI_AGENT_43: { JPM: 100, CASH: 745000 }.  Marked to market: 10696500
Final holdings for ZI_AGENT_44: { JPM: 287, CASH: -18909457 }.  Marked to market: 9651348
Final holdings for ZI_AGENT_45: { JPM: 72, CASH: 3066068 }.  Marked to market: 10231148
Final holdings for ZI_AGENT_46: { JPM: -200, CASH: 30588500 }.  Marked to market: 10685500
Final holdings for ZI_AGENT_47: { CASH: 10392900 }.  Marked to market: 10392900
Final holdings for ZI_AGENT_48: { JPM: 552, CASH: -44893620 }.  Marked to market: 10038660
Final holdings for ZI_AGENT_49: { JPM: 264, CASH: -16552868 }.  Marked to market: 9719092
Final holdings for ZI_AGENT_50: { JPM: 125, CASH: -2939451 }.  Marked to market: 9499924
Final holdings for ZI_AGENT_51: { JPM: 152, CASH: -5443684 }.  Marked to market: 9682596
Final holdings for HBL_AGENT_52: { JPM: -600, CASH: 69887600 }.  Marked to market: 10178600
Final holdings for HBL_AGENT_53: { JPM: -285, CASH: 39153253 }.  Marked to market: 10791478
Final holdings for HBL_AGENT_54: { JPM: -298, CASH: 40136146 }.  Marked to market: 10480676
Final holdings for HBL_AGENT_55: { JPM: -500, CASH: 60020800 }.  Marked to market: 10263300
Final holdings for HBL_AGENT_56: { JPM: -783, CASH: 88900686 }.  Marked to market: 10980441
Final holdings for HBL_AGENT_57: { CASH: 9983400 }.  Marked to market: 9983400
Final holdings for HBL_AGENT_58: { JPM: 377, CASH: -27573646 }.  Marked to market: 9943509
Final holdings for HBL_AGENT_59: { JPM: -100, CASH: 20178150 }.  Marked to market: 10226650
Final holdings for HBL_AGENT_60: { JPM: -462, CASH: 57036969 }.  Marked to market: 11061039
Final holdings for HBL_AGENT_61: { JPM: -415, CASH: 51678545 }.  Marked to market: 10379820
Final holdings for HBL_AGENT_62: { JPM: -400, CASH: 50202300 }.  Marked to market: 10396300
Final holdings for HBL_AGENT_63: { CASH: 10177660 }.  Marked to market: 10177660
Final holdings for HBL_AGENT_64: { JPM: 12, CASH: 9225104 }.  Marked to market: 10419284
Final holdings for HBL_AGENT_65: { JPM: 147, CASH: -4434496 }.  Marked to market: 10194209
Final holdings for HBL_AGENT_66: { JPM: -300, CASH: 40142600 }.  Marked to market: 10288100
Final holdings for HBL_AGENT_67: { JPM: 160, CASH: -5929580 }.  Marked to market: 9992820
Final holdings for HBL_AGENT_68: { JPM: -104, CASH: 20393688 }.  Marked to market: 10044128
Final holdings for HBL_AGENT_69: { JPM: 261, CASH: -15867092 }.  Marked to market: 10254049
Final holdings for HBL_AGENT_70: { JPM: 189, CASH: -8637374 }.  Marked to market: 10170961
Final holdings for HBL_AGENT_71: { JPM: -229, CASH: 33322608 }.  Marked to market: 10533673
Final holdings for HBL_AGENT_72: { JPM: -487, CASH: 59266688 }.  Marked to market: 10802883
Final holdings for HBL_AGENT_73: { JPM: 156, CASH: -5291556 }.  Marked to market: 10232784
Final holdings for HBL_AGENT_74: { JPM: 90, CASH: 1369160 }.  Marked to market: 10325510
Final holdings for HBL_AGENT_75: { JPM: 300, CASH: -19810000 }.  Marked to market: 10044500
Final holdings for HBL_AGENT_76: { JPM: -500, CASH: 61090400 }.  Marked to market: 11332900
Final holdings for MOMENTUM_AGENT_77: { JPM: -161, CASH: 24171913 }.  Marked to market: 8149998
Final holdings for MOMENTUM_AGENT_78: { JPM: -90, CASH: 17595284 }.  Marked to market: 8638934
Final holdings for MOMENTUM_AGENT_79: { JPM: -50, CASH: 14448396 }.  Marked to market: 9472646
Final holdings for MOMENTUM_AGENT_80: { JPM: -115, CASH: 20122930 }.  Marked to market: 8678705
Final holdings for MOMENTUM_AGENT_81: { JPM: -78, CASH: 16974034 }.  Marked to market: 9211864
Final holdings for MOMENTUM_AGENT_82: { JPM: -92, CASH: 18098826 }.  Marked to market: 8943446
Final holdings for MOMENTUM_AGENT_83: { JPM: -139, CASH: 21649384 }.  Marked to market: 7816799
Final holdings for MOMENTUM_AGENT_84: { JPM: -96, CASH: 18497590 }.  Marked to market: 8944150
Final holdings for MOMENTUM_AGENT_85: { JPM: -18, CASH: 11519088 }.  Marked to market: 9727818
Final holdings for MOMENTUM_AGENT_86: { JPM: -21, CASH: 11820999 }.  Marked to market: 9731184
Final holdings for MOMENTUM_AGENT_87: { JPM: -72, CASH: 16373372 }.  Marked to market: 9208292
Final holdings for MOMENTUM_AGENT_88: { JPM: -19, CASH: 11619943 }.  Marked to market: 9729158
Final holdings for MOMENTUM_AGENT_89: { JPM: -87, CASH: 17587686 }.  Marked to market: 8929881
Final holdings for MOMENTUM_AGENT_90: { JPM: -125, CASH: 21120780 }.  Marked to market: 8681405
Final holdings for MOMENTUM_AGENT_91: { JPM: -154, CASH: 23456023 }.  Marked to market: 8130713
Final holdings for MOMENTUM_AGENT_92: { JPM: -94, CASH: 17407033 }.  Marked to market: 8052623
Final holdings for MOMENTUM_AGENT_93: { JPM: -153, CASH: 23060669 }.  Marked to market: 7834874
Final holdings for MOMENTUM_AGENT_94: { JPM: -24, CASH: 12124240 }.  Marked to market: 9735880
Final holdings for MOMENTUM_AGENT_95: { JPM: -125, CASH: 20826053 }.  Marked to market: 8386678
Final holdings for MOMENTUM_AGENT_96: { JPM: -78, CASH: 16974034 }.  Marked to market: 9211864
Final holdings for MOMENTUM_AGENT_97: { JPM: -199, CASH: 27403359 }.  Marked to market: 7599874
Final holdings for MOMENTUM_AGENT_98: { JPM: -78, CASH: 16974034 }.  Marked to market: 9211864
Final holdings for MOMENTUM_AGENT_99: { JPM: -18, CASH: 11519072 }.  Marked to market: 9727802
Final holdings for MOMENTUM_AGENT_100: { JPM: -22, CASH: 11922289 }.  Marked to market: 9732959
Logging order book to file...
Traceback (most recent call last):
  File "abides.py", line 29, in <module>
    config = importlib.import_module("config.{}".format(config_file), package=None)
  File "/home/jiachengweng/miniconda3/envs/marl-oe/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/jiachengweng/marl-optimal-execution/config/rmsc02.py", line 280, in <module>
    log_dir=args.log_dir,
  File "/home/jiachengweng/marl-optimal-execution/Kernel.py", line 319, in runner
    agent.kernelTerminating()
  File "/home/jiachengweng/marl-optimal-execution/agent/ExchangeAgent.py", line 124, in kernelTerminating
    self.logOrderBookSnapshots(symbol)
  File "/home/jiachengweng/marl-optimal-execution/agent/ExchangeAgent.py", line 420, in logOrderBookSnapshots
    dfLog = pd.SparseDataFrame(dfLog)
TypeError: SparseDataFrame() takes no arguments
